### PR TITLE
Fixes to deepmap param

### PR DESCRIPTION
**Pull request by modulustx**
Made a few fixes to deepmap params and parsing of library file in order to get the pipeline to run.

### CODE REVIEW

**Comment by sminot** [comment]
Is the actual name "deepmap" or "depmap"? I was seeing "depmap" on the mageck docs page, but maybe they have a typo as well? cc @modulustx

**Comment by modulustx** [comment]
Yeah, I wasn't sure, because the tool ran when I changed it.

**Comment by modulustx** [comment]
When it was changed to "deepmap"

**Comment by sminot** [comment]
Well, there definitely was a mismatch between the docs and the code! The help text had "deepmap" listed, while the code was referencing "depmap".

Given that the online documentation refers to "depmap", my preference would be to conform on that notation for this functionality. Would it work if we made the update in that direction instead, for the sake of internal consistency?

**Comment by modulustx** [comment]
Yeah, that's the right direction to fix... just looked up what DepMap
references.

**Comment by sminot** [comment]
This should be resolved by a6d32f436efdf52332e972591d53ec4ca2a96e0c

Thanks for taking a look, and let me know if you'd like to add anything else to the pipeline!

**Pull request closed without merging**
